<?php

namespace LibraryBundle\Repository;

/**
 * CopyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopyRepository extends \Doctrine\ORM\EntityRepository
{
}
